# Settings in the [build] context are global and are applied to
# all contexts unless otherwise overridden by more specific contexts.
[build]
publish = "packages/graphiql"

# Default build command.
command = "pnpm build && pnpm build-bundles && pnpm build-docs && pnpm build-demo"
environment = { PNPM_FLAGS = "--frozen-lockfile" }
