#!/bin/bash

# Takes package@next and promotes it to package@latest for each package we manage.
function next2latest {
  V=$(npm info $1 dist-tags.next | xargs)
  npm dist-tags add $1@$V latest
}

echo "Enter OTP code:"
read otp
export NPM_CONFIG_OTP=$otp

next2latest graphql-language-service-types
next2latest graphql-language-service-parser
next2latest graphql-language-service-utils
next2latest graphql-language-service-interface
next2latest graphql-language-service-server
next2latest graphql-language-service
next2latest codemirror-graphql
next2latest graphiql
next2latest graphiql-example-cdn