packages:
  - packages/*
  - functions
  - packages/graphiql/test
  - examples/monaco-graphql-webpack
  - examples/monaco-graphql-nextjs
  - examples/monaco-graphql-react-vite
  - examples/graphiql-vite
  - examples/graphiql-vite-react-router
  - examples/graphiql-webpack

minimumReleaseAge: 4320
engineStrict: true
nodeLinker: isolated
linkWorkspacePackages: true

allowBuilds:
  '@vscode/vsce-sign': false
  core-js: false
  cypress: true
  ejs: false
  esbuild: false
  fsevents: false
  keytar: false
  msw: false

overrides:
  '@babel/traverse': ^7.23.2
  vscode-languageserver-types: 3.17.3
  markdown-it: 14.2.0
  react: 18.3.1
  react-dom: 18.3.1
  vite: 6.4.3

patchedDependencies:
  '@changesets/assemble-release-plan@6.0.3': resources/patches/@changesets+assemble-release-plan+6.0.3.patch
  js-green-licenses@4.0.0: resources/patches/js-green-licenses+4.0.0.patch
