#!/bin/bash

set -e

# Takes package@rc and promotes it to package@latest for each package we manage.
function rc2latest {
  V=$(npm info $1 dist-tags.rc | xargs)
  npm dist-tags add $1@$V latest
}

echo "Enter OTP code:"
read otp
export NPM_CONFIG_OTP=$otp

rc2latest graphql-language-service-types
rc2latest graphql-language-service-parser
rc2latest graphql-language-service-utils
rc2latest graphql-language-service-interface
rc2latest graphql-language-service-server
rc2latest graphql-language-service
rc2latest codemirror-graphql
rc2latest graphiql
rc2latest graphiql-example-cdn