projects:
  testWithSchema:
    schema:
      - __schema__/StarWarsSchema.graphql
      - 'directive @customDirective on FRAGMENT_SPREAD'
  testWithEndpoint:
    schema: https://example.com/graphql
  testWithEndpointAndSchema:
    schema:
      - __schema__/StarWarsSchema.graphql
      - https://example.com/graphql
  testWithoutSchema:
    schema: ''
  testWithCustomDirectives:
    schema:
      - __schema__/StarWarsSchema.graphql
      - 'directive @customDirective on FIELD'
  testSingularIncludesGlob:
    schema: __schema__/StarWarsSchema.graphql
    documents: __queries__/*.graphql
  testMultipleIncludes:
    schema: __schema__/StarWarsSchema.graphql
    documents:
      - __queries__/*.graphql
      - __fragments__/*.graphql
  testNoIncludes:
    schema: __schema__/StarWarsSchema.graphql
  testBadIncludes:
    schema: __schema__/StarWarsSchema.graphql
    documents: nope.nopeql
