name: Generic IDE (LSP Server) Bug 🐞
description: File any non syntax highlighting related bugs in vscode or any IDE lsp runtime (vim, intellij, emacs, sublime, etc), with the `graphql-language-service-server` / `graphql-lsp` CLI
title: "[lsp-server] 🐞 <title>"
labels: [bug, lsp-server]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of the issue you're experiencing.
      render: Markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      render: Markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this (redacted) graphql config with [filename]...
        3. Do '...' with [lsp client] 
        4. See errors in output channel, etc...
      render: Markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **LSP Server Version**: latest
          - **OS**: Ubuntu 20.04
          - **LSP Client**: vscode (`vscode-graphql`, etc), intellij-lsp, nvim coc, etc
      value: |
        - LSP Server Version:
        - OS:
        - LSP Client:
      render: Markdown
    validations:
      required: false

  - type: textarea
    attributes:
      label: Anything else?
      render: Markdown
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
