name: Vscode Syntax Bug
description: Report a bug for `monaco-graphql`
title: "[vscode-graphql-syntax] <title>"
labels: [vscode-graphql-syntax, bug, needs triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
