# .github/workflows/netlify.yml
name: Netlify Production Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'examples'
      - '!examples/monaco-graphql-webpack'

jobs:
  deploy:
    name: "Build & Deploy Production Demo & API Docs"
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Yarn Install
        uses: bahmutov/npm-install@v1
      # ( Build to ./dist or other directory... )

      - name: Build 
        run: yarn build

      - name: Build Bundles 
        run: yarn build-bundles

      - name: Build Typedoc
        run: yarn build-docs

      - name: Deploy Production Demo & Typedoc to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './packages/graphiql/'
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "GraphiQL 1 Demo"
          functions-dir: functions
          github-deployment-environment: "GraphiQL 1 Demo"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
        timeout-minutes: 1
