name: CI
on: [push]
      
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Yarn Install
        uses: bahmutov/npm-install@v1

      - name: Eslint
        run: yarn lint

      - name: Prettier Check
        run: yarn pretty-check

  build:
    name: Typescript Build
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Yarn Install
        uses: bahmutov/npm-install@v1

      - name: Tyescript Build
        run: yarn build

  unit:
    name: Unit Tests
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node: ['10', '12', '14', '16']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Yarn Install
        uses: bahmutov/npm-install@v1

      - run: yarn test --coverage

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          directory: coverage

  e2e:
    name: Cypress E2E Suite
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Yarn Install
        uses: bahmutov/npm-install@v1

      - name: Run E2E suite
        run: yarn e2e
