name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # Don't cancel a publish partway through!
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    environment: deploy
    name: Release
    runs-on: ubuntu-latest
    permissions:
      # To create a release, and to push branches:
      contents: write

      # To create/maintain the Changesets pull request
      pull-requests: write

      # PRs are backed by issues; this helps with stuff like reading labels/etc
      issues: read

      # To enable trusted publishing
      id-token: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn install --frozen-lockfile --immutable

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn ci:version
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          # for vscode marketplace, see https://github.com/microsoft/vscode-vsce/blob/194d59b975523696362ead891dc0f3ddd277b3bd/README.md#linux
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          # for ovsx, see https://github.com/eclipse/openvsx/blob/master/cli/README.md#publish-extensions
          OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}
